'use client'
import { useEffect, useMemo, useState } from 'react'
import { TopBar } from '@/components/strata/TopBar'
import { createClient } from '@/lib/supabase/client'
import { Link2, RefreshCw, Plus, Settings, ArrowRight, Calendar, CheckCircle2, AlertCircle, X } from 'lucide-react'

type Integration = { key:string; icon:string; name:string; desc:string; color:string; kind:'calendar'|'crm'|'payments'|'automation'|'analytics'|'ai' }
const ALL: Integration[] = [
  { key:'google_calendar', icon:'G', name:'Google Calendar', desc:'Sync real events into your schedule calendar.', color:'#4285F4', kind:'calendar' },
  { key:'stripe', icon:'S', name:'Stripe', desc:'Revenue and payment syncing.', color:'#635BFF', kind:'payments' },
  { key:'calcom', icon:'C', name:'Cal.com', desc:'Bookings and sales calls.', color:'#111827', kind:'calendar' },
  { key:'shopify', icon:'S', name:'Shopify', desc:'Orders, products, and store revenue.', color:'#7AB55C', kind:'payments' },
  { key:'hubspot', icon:'H', name:'HubSpot', desc:'CRM and marketing automation.', color:'#ff5c35', kind:'crm' },
  { key:'analytics', icon:'GA', name:'Google Analytics', desc:'Website traffic and conversion data.', color:'#F9AB00', kind:'analytics' },
  { key:'zapier', icon:'Z', name:'Zapier', desc:'Workflow automation.', color:'#ff4a00', kind:'automation' },
  { key:'openai', icon:'AI', name:'OpenAI / Groq', desc:'Optional AI API key for richer copilot answers.', color:'#26d36e', kind:'ai' },
]
function Card({ children, className='' }: { children: React.ReactNode; className?: string }) { return <div className={`fo-card ${className}`}>{children}</div> }
function Logo({ txt, bg }: { txt:string; bg:string }) { return <div className="w-11 h-11 rounded-lg flex items-center justify-center text-sm font-black shrink-0" style={{ background:bg, color:'#fff' }}>{txt}</div> }

export default function IntegrationsPage(){
  const [workspaceName,setWorkspaceName]=useState('My Workspace')
  const [tab,setTab]=useState<'All'|'Connected'|'Available'|'Requests'>('All')
  const [googleConnected,setGoogleConnected]=useState(false)
  const [requests,setRequests]=useState<string[]>([])
  const [toast,setToast]=useState('')
  const [customRequest,setCustomRequest]=useState('')
  const [serverConnections,setServerConnections]=useState<Record<string,string>>({})
  useEffect(()=>{(async()=>{const s=createClient(); const {data:{user}}=await s.auth.getUser(); if(!user)return; const [{data:ws},{data:settings}]=await Promise.all([s.from('workspaces').select('name').eq('owner_id',user.id).maybeSingle(), s.from('user_settings').select('google_cal_connected').eq('user_id',user.id).maybeSingle()]); if(ws?.name)setWorkspaceName(ws.name); setGoogleConnected(!!settings?.google_cal_connected); setRequests(JSON.parse(localStorage.getItem('integration-requests')||'[]')); const res=await fetch('/api/integrations').catch(()=>null); if(res?.ok){const j=await res.json(); const map:Record<string,string>={}; (j.integrations||[]).forEach((x:any)=>{map[x.provider]=x.status}); setServerConnections(map)}; const params=new URLSearchParams(window.location.search); if(params.get('error')==='oauth-not-configured' || params.get('error')==='not_configured'){setToast('Google Calendar needs GOOGLE_CLIENT_ID and GOOGLE_CLIENT_SECRET in .env.local before it can connect.')} if(params.get('connected')==='google_calendar'){setToast('Google Calendar connected.')} })()},[])
  const connectedKeys=useMemo(()=>new Set([...(googleConnected||serverConnections.google_calendar==='connected'?['google_calendar']:[]), ...Object.entries(serverConnections).filter(([,v])=>v==='connected').map(([k])=>k)]),[googleConnected,serverConnections])
  const connected=ALL.filter(i=>connectedKeys.has(i.key))
  const available=ALL.filter(i=>!connectedKeys.has(i.key))
  const visible=tab==='Connected'?connected:tab==='Available'?available:tab==='Requests'?ALL.filter(i=>requests.includes(i.key)):ALL
  const requestCustom=async()=>{ const name=customRequest.trim(); if(!name) return; const key=`custom:${name.toLowerCase().replace(/[^a-z0-9]+/g,'_').slice(0,40)}`; const next=[...new Set([...requests,key])]; setRequests(next); localStorage.setItem('integration-requests',JSON.stringify(next)); await fetch('/api/integrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:key,status:'requested',metadata:{name}})}).catch(()=>null); setCustomRequest(''); setToast(`${name} request saved`); setTimeout(()=>setToast(''),2200) }
  const request=async(i:Integration)=>{ if(i.key==='google_calendar'){ window.location.href='/api/auth/google-calendar'; return } const next=[...new Set([...requests,i.key])]; setRequests(next); localStorage.setItem('integration-requests',JSON.stringify(next)); await fetch('/api/integrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:i.key,status:'requested'})}).catch(()=>null); setToast(`${i.name} request saved`); setTimeout(()=>setToast(''),2200) }
  return <div className="flex flex-col h-full fo-page"><TopBar title="Integrations" workspaceName={workspaceName} hasData={connected.length>0} showGreeting />
    {toast&&<div className="fixed bottom-5 left-1/2 z-50 -translate-x-1/2 rounded-xl px-4 py-2 text-sm font-bold" style={{background:'var(--bg-card)',border:'1px solid var(--border-strong)'}}>{toast}</div>}
    <div className="flex-1 overflow-y-auto p-7 md:p-8 animate-in"><div className="max-w-[1100px] space-y-6">
      <div><h1 className="text-3xl font-black tracking-tight">Integrations</h1><p className="text-base mt-2" style={{ color:'var(--text-muted)' }}>Only real connected tools show as connected. Everything else can be requested or opened when setup exists.</p></div>
      <div className="grid grid-cols-3 gap-4"><Card className="p-5 flex items-center gap-5"><div className="w-14 h-14 rounded-full flex items-center justify-center" style={{ background:'rgba(39,211,110,.12)' }}><Link2 className="w-7 h-7 text-green-500"/></div><div><p className="text-3xl font-black fo-num">{connected.length}</p><p>Connected</p><p className="text-xs" style={{ color:'var(--text-muted)' }}>Real active integrations</p></div></Card><Card className="p-5 flex items-center gap-5"><div className="w-14 h-14 rounded-full flex items-center justify-center" style={{ background:'rgba(255,255,255,.04)' }}><Settings className="w-7 h-7 text-neutral-400"/></div><div><p className="text-3xl font-black fo-num">{available.length}</p><p>Available</p><p className="text-xs" style={{ color:'var(--text-muted)' }}>Not connected yet</p></div></Card><Card className="p-5 flex items-center gap-5"><div className="w-14 h-14 rounded-full flex items-center justify-center" style={{ background:'rgba(39,211,110,.12)' }}><RefreshCw className="w-7 h-7 text-green-500"/></div><div><p className="text-3xl font-black fo-num">{requests.length}</p><p>Requests</p><p className="text-xs" style={{ color:'var(--text-muted)' }}>Saved locally</p></div></Card></div>
      <Card className="overflow-hidden"><div className="flex items-center justify-between px-4 pt-3 border-b" style={{ borderColor:'var(--border)' }}><div className="flex gap-7">{(['All','Connected','Available','Requests'] as const).map(t=><button key={t} onClick={()=>setTab(t)} className="pb-3 text-sm font-bold" style={{ color:tab===t?'var(--accent)':'var(--text-secondary)', borderBottom: tab===t?'3px solid var(--accent)':'3px solid transparent' }}>{t}</button>)}</div><button onClick={()=>request(ALL[0])} className="mb-3 px-4 py-2 rounded-lg text-sm" style={{ background:'rgba(255,255,255,.035)', border:'1px solid var(--border)' }}><Calendar className="inline w-4 h-4 mr-1"/>Connect Google Calendar</button></div>
        <div className="p-4"><h2 className="text-xl font-bold mb-4">{tab} Integrations</h2><div className="divide-y" style={{ borderColor:'var(--border)' }}>{visible.length?visible.map((x)=><div key={x.key} className="flex items-center gap-4 py-3 px-3 rounded-lg hover:bg-white/[.035]"><Logo txt={x.icon} bg={x.color}/><div className="flex-1"><p className="font-bold">{x.name}</p><p className="text-sm" style={{ color:'var(--text-muted)' }}>{x.desc}</p></div>{connectedKeys.has(x.key)?<span className="px-3 py-1 rounded-md text-xs font-bold text-green-400" style={{ background:'rgba(39,211,110,.11)', border:'1px solid rgba(39,211,110,.22)' }}><CheckCircle2 className="inline w-3 h-3 mr-1"/>Connected</span>:<span className="px-3 py-1 rounded-md text-xs font-bold" style={{ color:'#fbbf24', background:'rgba(251,191,36,.08)', border:'1px solid rgba(251,191,36,.18)' }}><AlertCircle className="inline w-3 h-3 mr-1"/>Not connected</span>}<button onClick={()=>request(x)} className="px-4 py-2 rounded-lg text-xs font-bold" style={{ background:'rgba(255,255,255,.035)', border:'1px solid var(--border)' }}>{x.key==='google_calendar'?'Connect':requests.includes(x.key)?'Requested':'Request'}</button>{requests.includes(x.key)&&!connectedKeys.has(x.key)&&<button onClick={()=>{const n=requests.filter(r=>r!==x.key);setRequests(n);localStorage.setItem('integration-requests',JSON.stringify(n))}} className="w-9 h-9 rounded-lg hover:bg-white/5"><X className="inline w-4 h-4"/></button>}</div>):<p className="p-6 text-sm" style={{color:'var(--text-muted)'}}>Nothing here yet.</p>}</div></div>
        <div className="p-5 border-t" style={{ borderColor:'var(--border)' }}><div className="grid gap-3 md:grid-cols-[1fr_auto] items-center"><div><p className="font-black">Request something not listed</p><p className="text-xs" style={{color:'var(--text-muted)'}}>Tell us what tool you want FounderOS to support next.</p></div><div className="flex gap-2"><input className="input-base w-56" value={customRequest} onChange={e=>setCustomRequest(e.target.value)} placeholder="Airtable, QuickBooks, Discord..."/><button onClick={requestCustom} className="px-4 rounded-lg font-bold text-xs" style={{background:'var(--accent)',color:'#041008'}}>Request</button></div></div><p className="text-green-500 font-bold text-sm mt-4">No fake connection statuses. Connect Google Calendar or request future integrations. <ArrowRight className="inline w-4 h-4" /></p></div>
      </Card>
    </div></div></div>
}
